filebeat.inputs:
- type: docker
  enabled: true
  containers:
    path: "/var/lib/docker/containers"
    stream: "all"
    ids:
      - "*"
  multiline:
    pattern: '^[0-9]{4}[-/][0-9]{2}[-/][0-9]{2}[T ][0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}([-+][0-9]{4}|Z)?'
    negate: true
    match: after
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
        match_short_id: true
#### The next configurations is just for testing locally
    - drop_event:
        when:
          not:
            equals:
              docker.container.name: "app"

processors:
- add_cloud_metadata: ~
- rename:
    fields:
      - from: "host.name"
        to: "dockerhost"
      - from: "prospector.type"
        to: "log_type"
      - from: "source"
        to: "logger_name"
      - from: "stream"
        to: "level"
    ignore_missing: true
    fail_on_error: false
- drop_fields:
    fields: ["beat.hostname", "beat.name", "input.type", "prospector.type", "docker.container.labels", "host", "log.file.path"]

output.redis:
  hosts: ["redis:6379"]
  key: "filebeat"
  db: 0
  timeout: 5