filebeat.inputs:
- type: docker
  enabled: false
  containers:
    path: "/var/lib/docker/containers"
    stream: "all"
    ids:
      - "*"
  multiline:
    pattern: '^[0-9]{4}[-/][0-9]{2}[-/][0-9]{2}[T ][0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}([-+][0-9]{4}|Z)?'
    negate: true
    match: after
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
        match_short_id: true

- type: log
  enabled: true
  paths:
    #- /var/lib/docker/containers/*/*.log
    - /var/log/*.log
  processors:
    - add_cloud_metadata: ~
    - rename:
        fields:
          - from: "host.name"
            to: "dockerhost"
          - from: "prospector.type"
            to: "log_type"
          - from: "source"
            to: "logger_name"
          - from: "stream"
            to: "level"
        ignore_missing: true
        fail_on_error: false
    - drop_fields:
        fields: ["agent.hostname", "input.type", "prospector.type", "host", "log.file.path"]

logging.level: warning
logging.metrics.enabled: false
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

# output.logstash:
#   hosts: ["logstash:5044"]

output.redis:
  enabled: true
  hosts: ["redis:6379"]
  key: "filebeat"
  #ssl.verification_mode: "none"
  db: 0
  timeout: 5