#filebeat.inputs:
#- type: container
#  enabled: true
#  paths:
#    - "/var/lib/docker/containers/*/*.log"
#  multiline:
#    pattern: '^[0-9]{4}[-/][0-9]{2}[-/][0-9]{2}[T ][0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}([-+][0-9]{4}|Z)?'
#    negate: true
#    match: after
#  processors:
#    - add_docker_metadata:
#        host: "unix:///var/run/docker.sock"
#        match_short_id: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        -  config:
            - type: container
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              multiline:
                pattern: '^[0-9]{4}[-/][0-9]{2}[-/][0-9]{2}[T ][0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}([-+][0-9]{4}|Z)?'
                negate: true
                match: after
              processors:
                - add_docker_metadata:
                    host: "unix:///var/run/docker.sock"
                    match_short_id: true

processors:
- add_cloud_metadata: ~
- rename:
    fields:
      - from: "host.name"
        to: "dockerhost"
      - from: "input.type"
        to: "log_type"
      - from: "source"
        to: "logger_name"
      - from: "stream"
        to: "level"
    ignore_missing: true
    fail_on_error: false
- drop_fields:
    fields: ["agent.hostname", "input.type", "prospector.type", "container.labels", "host", "log.file.path"]

output.redis:
  hosts: ["redis:6379"]
  key: "filebeat"
  db: 0
  timeout: 5s