services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./var/log:/var/log
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    container_name: filebeat
    volumes:
      - ./ekl/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      #- /var/lib/docker/containers:/var/lib/docker/containers:ro
      #- /var/run/docker.sock:/var/run/docker.sock
      - ./var/log:/var/log

    command: >
      sh -c "chmod go-w /usr/share/filebeat/filebeat.yml &&
             filebeat -e -strict.perms=false -c /usr/share/filebeat/filebeat.yml"
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

    depends_on:
      - filebeat

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    container_name: logstash
    volumes:
      #- ./ekl/logstash/config:/usr/share/logstash/config
      - ./ekl/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./ekl/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    depends_on:
      #- elasticsearch
      - redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local